name: CI

on:
  pull_request:
    branches: [main]

jobs:
  deploy_blog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.25.1
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
      - name: install dependencies
        run: pnpm install
      - name: build
        run: pnpm build
      - name: deploy github pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
      - name: deploy cloudbase
        run: pnpm exec tcb login --apiKeyId ${{ secrets.CLOUDBASE_ID }} --apiKey ${{ secrets.CLOUDBASE_KEY }} && pnpm exec tcb hosting /home/runner/work/xiaofuyesnew.github.io/xiaofuyesnew.github.io/dist -e ${{ secrets.ENV_ID }}

      # - name: Install SSH Key
      #   uses: shimataro/ssh-key-action@v2
      #   with:
      #     key: ${{ secrets.REMOTE_SSH_KEY }}
      #     known_hosts: "just-a-placeholder-so-we-don't-get-errors"
      #     # known_hosts: ${{ secrets.KNOWN_HOSTS }}
      # - name: Adding Known Hosts
      #   run: ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
      # - name: Deploy to Server
      #   run: rsync -avz --delete /home/runner/work/xiaofuyesnew.github.io/xiaofuyesnew.github.io/dist/ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_TARGET }}
