name: CI

on:
  pull_request:
    branches: [main]

jobs:
  deploy_blog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.26.0
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
      - name: install dependencies
        run: pnpm install
      - name: build
        run: pnpm build
      - name: deploy github pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
      - name: deploy cloudbase
        run: |
          npm install @cloudbase/cli -g
          tcb login --apiKeyId ${{ secrets.CLOUDBASE_ID }} --apiKey ${{ secrets.CLOUDBASE_KEY }}
          tcb hosting delete / -e ${{ secrets.ENV_ID }}
          tcb hosting deploy dist -e ${{ secrets.ENV_ID }}
