name: CI

on:
  pull_request:
    branches: [master]

jobs:
  deploy_blog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Cache dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

      - name: Build Sites
        run: yarn build

      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.REMOTE_SSH_KEY }}
          known_hosts: "just-a-placeholder-so-we-don't-get-errors"
          # known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy to Server
        run: rsync -avz --delete /home/runner/work/xiaofuyesnew.github.io/xiaofuyesnew.github.io/dist/ ubuntu@139.198.170.14:/home/ubuntu/www/
